---
title: "Read, Listen & Watch"
output:
  html_document:
    fig_width: 1
---

## Things to read and listen to for economics students {#reading}

There is a lot of topical reading in economics at any time. However, these days, when it is obvious that not all salvation llies in free markets, economic thinking is more important than ever. This is briliantly demonstrated by [coronavirusandtheeconomy.com/](https://coronavirusandtheeconomy.com/), a collective initiative by the economic research community to answer questions from policy-makers and the public about the economics of the Covid-19 crisis and the recovery. A new article is published every day.

Interesting economics blogs and podcasts:

* [Econtalk](http://www.econtalk.org/){target="_blank"}, podcasts on a range of economics issues  
* [FiveThityEight](https://fivethirtyeight.com/economics/){target="_blank"}, Nate Silver's data-based news service  
* [Freakonomics](http://freakonomics.com/){target="_blank"}, blogs and podcasts following the pattern set by Steven D. Levitt and Stephen J. Dubner's successful Freakonomics book series   
* [Planet Money](http://planetmoney.com/){target="_blank"}, this is an Economics programme by National Public radio  
* [Tim Harford](http://timharford.com/){target="_blank"} is an Economist at the Financial Times and writes about economics of general interest and also presents the inspirational BBC Radio 4 [More or Less](https://www.bbc.co.uk/programmes/p02nrss1){target="_blank"} programme.
* [DailyEcon](https://sites.google.com/view/dailylifeecon/home) is a website with associated instagram account in which daily life situations are looked at through an Economic lens.


Interesting blogs:

* [Diane Coyle](http://www.enlightenmenteconomics.com/blog/){target="_blank"}, formerly of Manchester, now at The University of Cambridge. She reviews economics books and writes on the digital economy and its measurement.  
* [John H. Cochrane](https://johnhcochrane.blogspot.com/){target="_blank"}, "news, views, and commentary, from a humorous free-market point of view"  
* [Simon Wren-Lewis](https://mainlymacro.blogspot.com/){target="_blank"}, left of centre macroeconomist 
* [Microeconomic Insights](https://microeconomicinsights.org/){target="_blank"}, a blog which presents current high quality research for public consumption  
* [Marginal Revolution](https://marginalrevolution.com/){target="_blank"}
* [Noah Smith](http://noahpinionblog.blogspot.com/){target="_blank"}, Economist at Bloomberg
* [Nuno Palma](https://nofuturepast.wordpress.com/){target="_blank"}, Economist at University of Manchester blogging on all things Economic History


YouTube Channels and Videos:

* [Jacob Clifford](https://www.youtube.com/user/ACDCLeadership){target="_blank"}, produces videos on textbook level micro- and macroeconomics  
* [One Minute Economics](https://www.youtube.com/channel/UCpsroJwsVKQvRH3ZqdvRetQ){target="_blank"}, one minute animated clips on a range of economics issues  
* [Ted Ed](https://www.youtube.com/user/TEDEducation){target="_blank"}, TED talks on a range of interesting isssues  

Further links to to some Economics themed distractions are provided by the [Economics Network](http://www.studyingeconomics.ac.uk/the-little-bits-we-like/){target="_blank"}.

Twitter:

Under the [#EconTwitter](https://twitter.com/search?q=%23EconTwitter&src=typd){target="_blank"} you can find topical discussions on economic topics in the twittersphere. 

Books:

Here are some book suggestions by colleagues in the Department

* [The (Mis)Behavior of Markets](https://www.amazon.co.uk/Mis-Behaviour-Markets-Fractal-Reward/dp/1846682622) (by Benoit Mandelbrot)  -  a non-standard view on finance theory, nicely illustrating why theories fail, and why it is sometimes crucial to look at the problem from a different and creative perspective. It is also a very accessible introduction to the fractal theory, full of fun and interesting examples. Recommended by [Ekaterina Kazak](https://www.research.manchester.ac.uk/portal/ekaterina.kazak.html)
* Simon Kuper & Stefan Szymanski, [Soccernomics](https://www.amazon.co.uk/Soccernomics-England-Germany-France-Finally/dp/000823664X/ref=sr_1_1?dchild=1&keywords=Soccernomics&qid=1599205282&s=books&sr=1-1) - Originally published under the crowd pleasing title "Why England Lose" this book looks at a range of issues relating to the use of economics in football, using real world data to illustrate some quite startling findings, such as who was the most efficient Premier League manager. Reading this book might make you look again at the way football clubs behave, particularly as we head into what is likely to be a turbulent summer for many clubs. Recommended by Robert O'Neill.
* Terry Pratchett [Making Money](https://www.amazon.co.uk/Making-Money-Discworld-Novel-Novels/dp/0552167703) This one is not a formal Economics book but is a comic novel which contains a lot of economics as part of the backdrop, for example in a world without electricity the central bank relies on a hydraulic computer to model the economy, an odd idea taken from real life economics (see https://en.wikipedia.org/wiki/MONIAC). As we follow Moist von Lipwig on his task to take over the central bank on Ankh Morpork you might recognise more economics than you realised! Recommended by Robert O'Neill.
* [Saving the Media: Capitalism, Crowdfunding, and Democracy](https://g.co/kgs/VZYbhB) by Julia Cagé, recommended by [Carlo Reggiano](https://sites.google.com/view/carloreggianieconomics/). It is a short book (which suits me, as I am a very slow and easily distracted reader - many students may also be?). The first part documents with a lot of data trends in the media industry in the digital age, with focus on the production of news and the role of journalists. It then looks at the implications that the of the "media crisis" for the sector and for the democratic system more in general. Finally, the book tries to propose a new sustainable model (haven't got there, but I suspect this part may be the least convincing).
* [Down and Out in Paris and London](https://www.amazon.co.uk/Paris-London-Penguin-Modern-Classics/dp/0141184388/ref=sr_1_1?dchild=1&keywords=Down+and+Out+in+Paris+and+London&qid=1599205736&s=books&sr=1-1) by George Orwell, recommended by [Simon Peters](https://www.research.manchester.ac.uk/portal/simon.peters.html). I was advised by an old employer to read the works of George Orwell if I wanted to improve my written English style. This one is relevant because it documents elements of trying to get piece-work in the service industry, and a spell I think on the consumptive ward of a Paris hospital, both resonant of things going on presently.
* [The Frock Coated Communist](https://www.amazon.co.uk/Frock-Coated-Communist-Revolutionary-Friedrich-Engels/dp/0141021403/ref=sr_1_1?dchild=1&keywords=The+Frock+Coated+Communist&qid=1599205795&s=books&sr=1-1) by Tristan Hunt, recommended by [Simon Peters](https://www.research.manchester.ac.uk/portal/simon.peters.html). Biography of Frederick Engels, including stuff on his time at Manchester, and of course, his work with Marx, so its a background context for political economy. Engels used to wander from the Albert Club (for German emigres), now the Graphene Centre, via the postbox outside the student union (still there near the crossing) where he posted money to Marx. So there is also some local interest beyond him and Marx working in Chethams Library.
* [Taking Chances winning with probability](https://www.amazon.co.uk/Taking-Chances-Probability-John-Haigh/dp/0198526636/ref=sr_1_1?dchild=1&keywords=Taking+Chances+winning+with+probability&qid=1599205874&s=books&sr=1-1) by John Haigh, recommended by [Simon Peters](https://www.research.manchester.ac.uk/portal/simon.peters.html). This is a collection of applications of probability to games, including some you may have played during lockdown. It is a bit old now (1999), relatively speaking, but it has some of the classics, but some omissions (no Monty Hall if I recall). Should be accessible to anyone who has done either of the statistics units.
